title: Testing GitHub Pages
author: JLG@HLR
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  First testing of GitHub Pages creation to validate if useful for installation process guidelines of the network nodes.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme:minima
